import ThemeProvider from "@/context/ThemeProvider";
import "./globals.css";

export const metadata = {
  title: "Mahdi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-stapel">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
